### ISSUE TITLE
bug in `pix2ringpos` for southern cap

### ISSUE THREAD

**Issue by marius311** [ziotom78/Healpix.jl#108]
With v4.2.0, e.g. final pixel should not be first ring (entire southern cap has an issue):

```
julia> pix2ringpos(Resolution(4), 12*4^2)
(:southcap, 1, 4)
```

**Comment by ziotom78** [comment]
Hi @marius311 , thanks for the report! I implemented that function in 2019, and it seems that I completely skipped the implementation of tests, what a shame!

I fixed the bug and added proper tests, I'll release a new bugfix version very soon.
