### ISSUE TITLE
Issue with Resolution struct in query functions

### ISSUE THREAD

**Issue by 3r3m0s** [ziotom78/Healpix.jl#112]
Giving the queryDiscRing function implausible values (e.g. in degree) with a radius larger than pi throws the wrong error because the field name for the pixel count of a given resolution hasn't been updated for this case:
`
using Healpix
nside = 8
m = HealpixMap{Float64, RingOrder}(nside)
res=Resolution(nside)
pix=queryDiscRing(res,5, 180, 5)`

gives the error:
ERROR: LoadError: type Resolution has no field npix

**Comment by ziotom78** [comment]
Hi @3r3m0s , thanks for the report! The `master` branch has a fix, might you please check that this works? If it is so, I'll release version 4.2.2.

**Comment by 3r3m0s** [comment]
Sorry maybe you should close it..
