### ISSUE TITLE
`ang2pixRing` error at boundaries for Float32 input?

### ISSUE THREAD

**Issue by kcarloni** [ziotom78/Healpix.jl#118]
```julia
julia> ang2pixRing( Resolution(128), Float32(pi), 0. )
ERROR: DomainError with 3.1415927:
Invalid value of theta
Stacktrace:
 [1] ang2pixRing(resol::Resolution, theta::Float32, phi::Float64)
   @ Healpix ~/.julia/packages/Healpix/QiFKK/src/pixelfunc.jl:289
 [2] top-level scope
   @ REPL[2]:1
```

I get the same error for `ang2pixRing( Resolution(128), Float32(pi), Float32(0.287) )`

**Comment by hsgg** [comment]
Yah, I ran into the same problem some years ago. The problem is that the closest Float32 value to pi is larger than pi:
```
julia> Float32(pi) > pi
true
```
I think I solved it by using `prevfloat()`.

**Comment by ziotom78** [comment]
Yeah, I believe the error message produced by Healpix.jl is clear: `DomainError with 3.1415927 - Invalid value of theta`, because π=3.1415926535897932384626433…
