### ISSUE TITLE
some options for spherical harmonics

### ISSUE THREAD

**Issue by xzackli** [ziotom78/Healpix.jl#20]
I see a few possible ways to get map2alm/alm2map into Healpix.jl.

1. Call FastTransforms.jl. This may require some coordination with the author -- I think HEALPix needs rings of both even and odd size? This has been discussed in the context of LibHealpix.jl. https://github.com/JuliaApproximation/FastTransforms.jl/issues/28
2. Wrap Libsharp ([Reinecke and Seljebotn 2013](http://arxiv.org/abs/1303.4945)), which I think some HEALPix implementations use. This is nice from a standards point of view, since we're also using Libsharp on rectangular pixelizations (plate carrée) in LSSTDESC/NaMaster and simonsobs/pixell. This would probably involve some C linker suffering and BinaryBuilder, maybe resulting in a LibSharp.jl which would depend on Healpix.jl.
3. Port map2alm from an existing HEALPix implementation into Healpix.jl. This would probably be the most work and also the slowest.

Finally, to get science done I'm currently just wrapping healpy through PyCall, which is not ideal but could be sufficient. 

Thoughts?

**Comment by ziotom78** [comment]
Dear @xzackli, I have a surprise for you!

https://github.com/ziotom78/libsharp.jl

I created this repo a few days ago (coincidence!) and have not written any wrapper, but it uses your 2nd option through BinaryBuilder (see https://github.com/JuliaBinaryWrappers/libsharp2_jll.jl). The big thing is that the wrapper works under Windows too! If you are familiar with the libsharp C interface, you might submit some PRs to libsharp.jl: I would be really happy to merge them!

**Comment by xzackli** [comment]
This is terrific, I love it! I have some familiarity with the C interface but not BinaryBuilder, but I'd love to poke around.
