### ISSUE TITLE
[Question] implementation of query disc

### ISSUE THREAD

**Issue by aurelio-amerio** [ziotom78/Healpix.jl#27]
Hello, this Julia library seems wonderful and I'm really interested in using it over healpy. I was wondering how hard it would be to implement the `query_disc` function and if there is anybody currently working on it.
Thank you!

**Comment by ziotom78** [comment]
Hi @aurelio-amerio , AFAIK at the moment nobody is working on the `query_disc` function. I don't believe it would be too hard to implement. For reference, the Healpix C++ library implements it in ~200 lines of code: https://github.com/healpy/healpixmirror/blob/trunk/src/cxx/Healpix_cxx/healpix_base.cc#L153-L321 .

**Comment by xzackli** [comment]
I needed a query disc so I put together a test using NearestNeighbors.jl -- it was pretty slow (factor of 5-10). It seems like writing our own would definitely be faster compared to balltree, since we know the structure of healpix already.
