### ISSUE TITLE
Rename `readfullweights` and `applyfullweights!`

### ISSUE THREAD

**Issue by ziotom78** [ziotom78/Healpix.jl#56]
The case of the two new functions `readfullweights` and `applyfullweights!` to be included in release 3.0 does not match the camel-case standard used for other functions:

- `ringWeightPath`
- `readWeightRing`
- `pixelWindowPath`
- `readPixelWindowT`
- etc.

Although the common practice in Julia is to use all-lowercase identifier, I believe the least disruptive change would be to convert to CamelCase the two functions, i.e., `readFullWeights` and `applyFullWeights!`.

@xzackli, what do you think?

**Comment by xzackli** [comment]
I think changing those functions to camel case would be fine -- the package is currently split into "foo2bar" and camel case methods, and I think that is ok. Makes sense to enforce consistency!

**Comment by ziotom78** [comment]
Fixed by #55.
