### ISSUE TITLE
Cannot read Healpix map 

### ISSUE THREAD

**Issue by fincardona** [ziotom78/Healpix.jl#6]
I tried to open a Healpix map using the following syntax 

` a = Hp.readMapFromFITS("/home/federico/Dropbox/STRIP/ScanningStrategy/new_hit_maps/IO.fits", 1, Float64)`

where Hp is an alias for Healpix, but I obtain the following error:

`ERROR: While processing file '/home/federico/Dropbox/STRIP/ScanningStrategy/new_hit_maps/IO.fits: could not open the named file
Stacktrace:
 [1] fits_assert_ok(::Int32, ::String) at /home/federico/.julia/v0.6/FITSIO/src/libcfitsio.jl:207
 [2] fits_open_table(::String, ::Int64) at /home/federico/.julia/v0.6/FITSIO/src/libcfitsio.jl:282
 [3] readMapFromFITS(::String, ::Int64, ::Type{Float64}) at /home/federico/.julia/v0.6/Healpix/src/Healpix.jl:521
`

The map has been saved using:

`Hp.saveToFITS(hit_map, join(["!./", db.focalplane["I0"].name, ".fits"]), typechar = "D")`

Thanks

**Comment by ziotom78** [comment]
Works for me:
```julia
import Healpix
m1 = Healpix.Map{Float64, Healpix.RingOrder}(zeros(Float64, 12))
filename = "test.fits"
Healpix.saveToFITS(m1, filename)
m2 = Healpix.readMapFromFITS(filename, 1, Float64)
println("Are the two maps equal? $(m1.pixels == m2.pixels)")
# Output: "Are the two maps equal? true"
```

**Comment by ziotom78** [comment]
Solved, as learned through private communication (!).
