### ISSUE TITLE
save FITS map with custom Header

### ISSUE THREAD

**Issue by fincardona** [ziotom78/Healpix.jl#7]
Is it possible to save additional (customized) information about a Healpix map using the function `Healpix.saveToFITS`, e.g. into the Header of the FITS file?   

Thanks

**Comment by ziotom78** [comment]
Something like this should work:
```julia
import Healpix
import FITSIO
f = FITSIO.fits_create_file(fileName)
FITSIO.fits_create_binary_tbl(f, 0, [("PIXELS", "1D", unit)], extname)
Healpix.saveToFITS(mymap, f, 1)
FITSIO.fits_update_key(f, "MYKEY", myvalue, "My comment")
FITSIO.fits_close_file(f)
```

For more information, just type `?Healpix.saveToFITS` or have a look at [`FITSIO`](https://github.com/JuliaAstro/FITSIO.jl) documentation.
