### ISSUE TITLE
Drop support for Julia 1.3?

### ISSUE THREAD

**Issue by ziotom78** [ziotom78/Healpix.jl#70]
Now that [Julia 1.7 has been released](https://discourse.julialang.org/t/julia-v1-7-0-has-been-released-and-v1-6-is-now-lts/72336), the intent of Julia developers is to make Julia 1.6 the new LTS release. They explicitly [advise against using older version of Julia](https://julialang.org/downloads/):

> Almost everyone should be downloading and using the latest stable release of Julia. Great care is taken not to break compatibility with older Julia versions, so older code should continue to work with the latest stable Julia release. You should only be using the long-term support (LTS) version of Julia if you work at an organization where implementing or certifying upgrades is prohibitively expensive and there is no need for new language features or packages…

I am opening this issue to consider the possibility to drop support for Julia 1.3 (the oldest version tested in our CI builds) and mark ≥1.6 as the Julia compiler we will use for any future development of Healpix.jl. (Consider that Healpix.jl ≤ 3.0 will always be available for those forced to use older versions of Julia.)

I would like to learn if there are use cases where preserving compatibility for future releases of Healpix.jl with Julia <1.6 is important. If we agree to drop support for Julia 1.3, I will modify PR #69 to remove Julia 1.3 from the test matrix and will release a new version, Healpix.jl 4.0.0.

I will keep this issue open for one week, so please tell me your thoughts!

**Comment by giordano** [comment]
My general approach is to not preemptively drop support for older versions: I'll keep supporting them (even if older than LTS) if that doesn't require much extra effort on the developers' side. As soon as I realise there are too many `if VERSION` or similar constructs, or if I have to use more complicated old syntax when better one is available, then I'll drop the support for older versions. I'm not sure what's the situation in this package in particular, but it may be a rule of thumb to consider

**Comment by ziotom78** [comment]
Thanks @giordano , you are the only one that commented, so I think that we can pick your approach (which saves us from releasing a new version!). I will simply include `nightly` and `1.3` in the test matrix.
