### ISSUE TITLE
getting back coordinates(vertices) from equirectangular projection

### ISSUE THREAD

**Issue by lazarusA** [ziotom78/Healpix.jl#77]
Say I do 

```Julia
nside = 8
m = HealpixMap{Float64,RingOrder}(nside)
m.pixels[:] = 1:length(m.pixels)
```

and then using Plots I can see a nice picture

```
plot(m, equirectangular)
```
I would rather like to have a `set` of points (lon, lat,) for each element `pix`, the vertices for each new pix tessellation. Let's say that instead of doing a heatmap I would like to do a wireframe with these points. Is there an in-built function for this? or a combination of the ones already available that might help. I went trough the docs without so much luck.

**Comment by lazarusA** [comment]
Yes, that's exactly what I'm looking for.

**Comment by ziotom78** [comment]
Hi @lazarusA , commit #81 implements the `boundariesRing` function, which should be close to what you were looking for. See the example in the documentation for a nice 3D plot of a tessellated sphere.

**Comment by lazarusA** [comment]
thanks.

**Comment by lazarusA** [comment]
I forgot to mention, that is currently being use here: https://lazarusa.github.io/ClimateVisualisations/appt2m_healpix.html Thanks again.

**Comment by ziotom78** [comment]
@lazarusA very nice, thank you for the link!
