### ISSUE TITLE
Bug in `queryDiscRing` ?

### ISSUE THREAD

**Issue by LudwigBoess** [ziotom78/Healpix.jl#87]
Hi,
I get a method call error when using `queryDiskRing` in very rare cases.
Backtracing the error lead me to this [line](https://github.com/ziotom78/Healpix.jl/blob/ad8b46e81976011e49bbf1cf8e0594da612f49ef/src/query.jl#L163).

Changing it to 
```julia
ringinfo = getringinfo(resol, irmax + 1)
```
fixed it for me.

**Comment by ziotom78** [comment]
Thanks for the report! Might you please provide the parameters (`NSIDE`, θ, φ, radius) that cause the error, so that I can add a new test case for this and fix the code?

**Comment by ziotom78** [comment]
Never mind, I was able to find a test case by trial and error.
