### ISSUE TITLE
type-dependent bug in ang2pixRing

### ISSUE THREAD

**Issue by ezaron** [ziotom78/Healpix.jl#93]
I noticed that ang2pixRing can return a result greater than the number of pixels if given a float32 input:
```
using Healpix
res=Resolution(1)
i = ang2pixRing(res,2.529,-1.74f-7)
j = ang2pixRing(res,2.529,-1.74e-7)
```
returns i=13 (incorrect) and j=12 (correct)

**Comment by ziotom78** [comment]
Thanks @ezaron , sorry for the slow response. I'll check what's the culprit for this bug.
