### ISSUE TITLE
`mollweideproj` and `mollweideprojinv`

### ISSUE THREAD

**Issue by LudwigBoess** [ziotom78/Healpix.jl#97]
I'm trying to get the pixel in the mollweide projection for a given position `pos` via `(theta, phi) = vec2ang(pos...)`.
I played around with it by trying to invert the `project` function and came accross this behaviour:

```julia
# dummy input variables
x_in = -0.5
y_in = -0.05

visible, lat, long = mollweideprojinv(x_in, x_in)
visible, x, y         = mollweideproj(lat, long)

x == x_in # this gives false
y == y_in # this gives false
```

I must be making some simple mistake here, could you please help me out?

I'm a bit confused because the wikipedia article you reference says the projection requires a root-finding step, so if I cange the `mollweideproj` function to:

```julia
using Roots

"""
    mollweideproj(lat, lon)

Mollweide projection. Given the latitude `lat` (in radians) and the
longitude (in radians), return a tuple (Bool, Number, Number) where the
first Boolean is a flag telling if the point falls within the projection (true)
or not (false), and the two numbers are the x and y coordinates of the point
on the projection plane (both are in the range [−1, 1]).
"""
function mollweideproj(lat, lon)
    f(θ) = asin( (2θ + sin(2θ))/π ) - lat
    θ    = find_zero(f, lat)

    (true, 2/π * lon * cos(θ), sin(θ))
end
```
I at least get the correct `y`, but not the correct `x`.

**Comment by ziotom78** [comment]
Hi, sorry for the very late answer! You're right, the `mollweideproj` implementation was just a stub (it's never used in the codebase), but it's worth to implement it correctly. I'll work on this in the next days, thanks for the report!

**Comment by ziotom78** [comment]
The bug should be fixed, it will be included in the next release.
